version: '3'

services:
  ais-digital-challenge:
    container_name: ais-digital-challenge
    build: '.'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - postgres-ais-digital
    networks:
      - app-connect
    ports:
      - '3000:3000'

  postgres-ais-digital:
    container_name: postgres-ais-digital
    image: postgres:12
    restart: unless-stopped
    volumes:
      - postgres-ais-digital-data:/data
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
    networks:
      - app-connect

volumes:
  postgres-ais-digital-data:

networks:
  app-connect:
      driver: bridge